---
- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
  - name: Terminate,stop or reboot instances that were previously launched
    ec2_instance:
      # region: "{{ deployment_region }}"
      state: "{{ instance_state }}"
      # filters:
      instance_ids:
        - "{{ lookup('aws_ssm', '/JJTech/{{ team }}/{{ application }}', region='us-east-2') }}"
        # instance-state-name: running
    # tag:
    #   App_Name: "{{App_Name}}"
    # ec2:
    #   state: "{{ instance_state }}"
    #   instance_ids: "{{ lookup('aws_ssm', '/JJTech/{{ team }}/{{ instance_ids }}', region='us-east-2') }}"