---
- hosts: webservers
  become: yes
  become_user: root
  become_method: sudo
  tasks:
  - name: enable nginx1 in amazon-linux-extras
    shell: "amazon-linux-extras enable nginx1"
  - name: install nginx using yum package manager
    yum:
      name: nginx
      state: latest
  - name: start nginx service
    service:
       name: nginx
       state: started
       enabled: true
##  become: yes
